# cuckoo-setup/configs/cuckoo.conf

[cuckoo]
version_check = no
delete_original = no
delete_bin_copy = no
machinery = virtualbox
memory_dump = no
terminate_processes = no
reschedule = no
process_results = yes
max_analysis_count = 0
max_machines_count = 0
max_vmstartup_count = 10
freespace = 1024
tmppath = 
rooter = 

[resultserver]
ip = 192.168.56.1
port = 2042
store_csvs = yes
upload_max_size = 134217728

[processing]
analysis_size_limit = 134217728
resolve_dns = yes
sort_pcap = yes

[database]
connection = 
timeout = 60

[timeouts]
default = 120
critical = 60
vm_state = 60