# cuckoo-setup/configs/routing.conf

[routing]
route = internet
internet = eth0
rt_table = main
auto_rt = yes
drop = no

[inetsim]
enabled = no
server = 192.168.56.1
ports = 

[tor]
enabled = no
dnsport = 5353
proxyport = 9040

[vpn]
enabled = no
vpns = 

[internet]
enabled = yes
interface = eth0