# cuckoo-setup/configs/virtualbox.conf

[virtualbox]
mode = headless
path = /usr/bin/VBoxManage
interface = vboxnet0
machines = CuckooVM1

[CuckooVM1]
label = CuckooVM1
platform = windows
ip = 192.168.56.101
snapshot = clean_snapshot
interface = 
resultserver_ip = 192.168.56.1
resultserver_port = 2042
tags = 
options = 
osprofile =